name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd eiretube  # Navigate to the directory containing the package.json file
        npm install
        
    - name: Build frontend
      run: |
        cd eiretube
        npm run build

    - name: Create build directory in backend
      run: |
        mkdir -p eiretube/backend/build

    - name: Copy frontend build to backend
      run: |
        cp -r eiretube/build/* eiretube/backend/build/

    - name: Zip files for deployment
      run: |
        cd eiretube/backend
        zip -r deploy-package.zip .

    - name: Deploy to EC2
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$EC2_KEY"
        echo "$EC2_HOST"
        echo "$EC2_USER"
        scp -o StrictHostKeyChecking=no -i $EC2_KEY app.zip $EC2_USER@$EC2_HOST:/home/$EC2_USER/
        ssh -o StrictHostKeyChecking=no -i $EC2_KEY $EC2_USER@$EC2_HOST 'unzip -o /home/$EC2_USER/app.zip -d /home/$EC2_USER/app && cd /home/$EC2_USER/app && npm install && pm2 restart all'

    - name: Restart Nginx
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i $EC2_KEY $EC2_USER@$EC2_HOST 'sudo systemctl restart nginx'



