name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd eiretube  # Navigate to the directory containing the package.json file
        npm install
        
    - name: Build frontend
      run: |
        cd eiretube
        npm run build

    - name: Create build directory in backend
      run: |
        mkdir -p eiretube/backend/build

    - name: Copy frontend build to backend
      run: |
        cp -r eiretube/build/* eiretube/backend/build/

    - name: Zip files for deployment
      run: |
        cd eiretube/backend
        zip -r deploy-package.zip .

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ec2-user@EC2_HOST:eiretube/eiretube

    - name: Execute remote commands
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@EC2_HOST << 'EOF'
          cd eiretube/eiretube
          npm install
          npm run build
          npm start
        EOF


